[package]
name = "ctap-hid-fido2"
version = "2.2.1"
authors = ["gebo <35388172+gebogebogebo@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

license="MIT"
description="Rust FIDO2 CTAP library"
repository="https://github.com/gebogebogebo/ctap-hid-fido2"
keywords=["FIDO2","CTAP"]
readme="README.md"

[dependencies]
hidapi = "1.2.3"
serde_cbor = "0.11.1"
num = "0.4.0"
hex = "0.4.2"
byteorder = "1.3.4"
ring = "0.16.20"
rust-crypto = "0.2"
x509-parser = "0.13"
base64 = "0.13.0"
hmac = "0.12"
anyhow = "1.0"
serde = "1.0.126"
strum = "0.24"
strum_macros = "0.24"
pad = "0.1.6"
